# Generated by Django 5.0.6 on 2024-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_livro', models.CharField(max_length=30)),
                ('nome_autor', models.CharField(max_length=20)),
                ('imagem', models.ImageField(upload_to='imagem/')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
