# Generated by Django 5.1.2 on 2024-10-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
