# Generated by Django 5.1 on 2024-08-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professores',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ano',
        ),
        migrations.AddField(
            model_name='turma',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
