# Generated by Django 5.0.6 on 2024-05-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='cpf',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
