# Generated by Django 5.0.6 on 2024-05-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_dados_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='telefone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
