# Generated by Django 5.0.6 on 2024-05-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_dados_email_dados_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='etinia',
            field=models.CharField(default='Sem Valor', max_length=20),
            preserve_default=False,
        ),
    ]
