# Generated by Django 5.0.6 on 2024-06-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_dados_etinia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil/'),
        ),
    ]
