# Generated by Django 5.0.6 on 2024-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_dados_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='doc',
            field=models.FileField(default='Sem Valor', upload_to='documento/'),
            preserve_default=False,
        ),
    ]
