# Generated by Django 5.0.6 on 2024-06-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=25)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imagem', models.ImageField(upload_to='imagem_produto')),
            ],
        ),
    ]
