# Generated by Django 5.0.6 on 2024-06-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0002_login_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='foto',
            field=models.ImageField(default='sem valor', upload_to='foto_usuario'),
            preserve_default=False,
        ),
    ]
