# Generated by Django 5.1 on 2024-09-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.TextField(max_length=8),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img_produto',
            field=models.ImageField(upload_to='imagem_produto/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valorComDesconto',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valorSemDesconto',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
