# Generated by Django 5.1 on 2024-08-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produto_img_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=5)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.AlterField(
            model_name='produto',
            name='valorComDesconto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valorSemDesconto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
