# Generated by Django 5.1 on 2024-09-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientes_cep_alter_produto_img_produto_and_more'),
        ('core', '0004_clientes_delete_cliente_and_more'),
    ]

    operations = [
    ]
