# Generated by Django 5.1 on 2024-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20240902_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default='1', max_length=254),
            preserve_default=False,
        ),
    ]
