# Generated by Django 5.1 on 2024-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_compra_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompra',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='produto',
            name='valorComDesconto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valorSemDesconto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
