# Generated by Django 5.1 on 2024-10-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_compra_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
