# Generated by Django 5.1 on 2024-08-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=150)),
                ('cep', models.TextField(max_length=11)),
                ('endereco', models.TextField(max_length=40)),
                ('bairro', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=40)),
                ('tamanho', models.CharField(choices=[('P', 'Pequena'), ('M', 'Media'), ('G', 'Grande')], max_length=2)),
                ('pedido', models.CharField(choices=[('NL', 'No local'), ('D', 'Delivere')], max_length=2)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
