# Generated by Django 5.1 on 2024-08-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maisPizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='sem valor', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='maisPizza.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido',
            field=models.CharField(choices=[('NL', 'No local'), ('D', 'Delivery')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande')], max_length=2),
        ),
    ]
