# Generated by Django 5.0.6 on 2024-05-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.CharField(choices=[('AC', 'Ação'), ('FI', 'Ficção'), ('DR', 'Drama'), ('AV', 'Aventura'), ('TR', 'Terro')], max_length=2)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
