# Generated by Django 5.0.6 on 2024-05-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
