# Generated by Django 5.0.6 on 2024-05-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dorama', '0002_dadospessoais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dadosPessoais',
        ),
    ]
