# Generated by Django 5.0.6 on 2024-07-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='imagem',
            field=models.ImageField(default='sem nome', upload_to='foto_produto/'),
            preserve_default=False,
        ),
    ]
