# Generated by Django 5.1.2 on 2024-10-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('P', 'Pequena'), ('M', 'Media'), ('G', 'Grande'), ('GG', 'Extra Grande')], max_length=2)),
                ('sabor', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imagem', models.ImageField(upload_to='imagem_pizza/')),
            ],
        ),
    ]
