# Generated by Django 5.0.6 on 2024-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço')),
                ('imagem', models.ImageField(upload_to='imagem/')),
                ('manual', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
