# Generated by Django 5.0.7 on 2024-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BergPizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Cliente',
            field=models.CharField(default='nd', max_length=50),
            preserve_default=False,
        ),
    ]
