# Generated by Django 5.0.7 on 2024-07-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BergPizza', '0002_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default='nda', on_delete=django.db.models.deletion.CASCADE, to='BergPizza.cliente'),
            preserve_default=False,
        ),
    ]
