# Generated by Django 5.0.7 on 2024-07-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BergPizza', '0003_remove_pedido_cliente_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
