# Generated by Django 5.1 on 2024-08-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default='1', upload_to='foto_perfil/'),
            preserve_default=False,
        ),
    ]
