# Generated by Django 5.0.6 on 2024-05-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('rg', models.PositiveBigIntegerField()),
                ('cpf', models.PositiveBigIntegerField()),
                ('data_nascimento', models.DateField()),
                ('profisao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='longin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
