# Generated by Django 5.0.6 on 2024-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='longin',
        ),
    ]
