# Generated by Django 5.0.6 on 2024-05-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dados', '0002_tipo_sexo_delete_longin'),
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Tipo_sexo',
        ),
    ]
