# Generated by Django 5.0.7 on 2024-07-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
                ('numero_telefone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=40)),
                ('pizza_t', models.CharField(choices=[('P', 'Pequena'), ('M', 'Media'), ('G', 'Grande'), ('GG', 'Grande Grande')], max_length=2)),
                ('pedido', models.CharField(choices=[('NL', 'No local'), ('D', 'Delivere')], max_length=2)),
            ],
        ),
    ]
