# Generated by Django 5.0.6 on 2024-05-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estudante', models.CharField(choices=[('P', 'Primario'), ('F', 'Fundamento'), ('M', 'Medio'), ('S', 'Superior')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
