# Generated by Django 5.0.6 on 2024-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('matricula', models.PositiveBigIntegerField()),
            ],
        ),
    ]
