# Generated by Django 5.1 on 2024-08-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=150)),
                ('zip_code', models.TextField(max_length=11)),
                ('address', models.TextField(max_length=150)),
                ('neighborhood', models.TextField(max_length=150)),
                ('number', models.TextField(max_length=5)),
                ('city', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=3, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
