# Generated by Django 5.1 on 2024-08-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maisPizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('P', 'Pequena'), ('M', 'Media'), ('G', 'Grande')], max_length=2)),
                ('pedido', models.CharField(choices=[('NL', 'No local'), ('D', 'Delivere')], max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='nome',
            new_name='sabor',
        ),
    ]
