# Generated by Django 5.1 on 2024-08-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maisPizza', '0002_pedido_rename_nome_pedidos_sabor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='sabor',
            new_name='nome',
        ),
    ]
